---
# Playbook to install and setup suggestd

- name: Check if suggestd is already present
  shell: which suggestd
  register: install_state
  ignore_errors: yes

- name: Installation skip message
  debug:
    msg: "suggestd already installed and force_install == false; skipping installation"
  when: install_state is success and force_install == false

- name: Force install message
  debug:
    msg: "suggestd already installed; reinstalling it (force_intall == true)"
  when: install_state is success and force_install == true

- include: install_suggestd.yml
  when: install_state is failed or force_install == true
