---

- name: Install Sphinx package
  apt:
    name: sphinxsearch
    state: present

- name: Install additional systemd.unit file
  copy:
    src: sphinxsearch.service
    dest: /etc/systemd/system/sphinxsearch.service
    owner: root
    group: root
    mode: 0644

- name: Remove init.d files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/init.d/sphinxsearch
    - /etc/default/sphinxsearch
